obj-m += snd-soc-skl-hda-dsp-independent-hp.o
snd-soc-skl-hda-dsp-independent-hp-y := skl_hda_dsp_generic.o

ccflags-y += -I$(srctree)/sound/soc/intel/boards
ccflags-y += -I$(srctree)/sound/soc/sof/intel
ccflags-y += -I$(srctree)/sound/soc/codecs
