{ lib }:
{
  username = "isning";
  userfullname = "ISNing";
  useremail = "isning_sf@outlook.com";
  networking = import ./networking.nix { inherit lib; };
  # generated by `mkpasswd -m scrypt --rounds=11`
  # https://man.archlinux.org/man/crypt.5.en
  initialHashedPassword = "$7$GU..../....F0fYlFmcRHM96npgwEnE//$7CwjPLsjeXSPD4ejNGMbx2LN1swCV6sGRoJmuSxtSV3";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  mainSshAuthorizedKeys = [
    # The main ssh keys for daily usage
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN/wxdP/w0q2X9SELC4y4F81dYYUew/baMlO5dgJZy49 isning@saika"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKRpXtuI08Cq+6xNOCanfP4SUaIcUZoReXHhxXT0kUAo isning@amiya"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG4yUfU+27vsRWhX/6a8SL488JAocphdDDx4IvbW19rz isning@bitwarden"
  ];
  secondaryAuthorizedKeys = [
    # the backup ssh keys for disaster recovery
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGVXlSkmuK1xLeqEY3knH9DdMjwByft+1dHEC1qXXaFY isning@backup"
  ];
}
